name: Mys
author: mystery
version: 1.3.0
description: Das CMDPlugin

main: de.mystery.cmd.anfang

commands:
      ts:
        usuage: /ts
      web:
        usuage: /web
      webseite:
        usuage: /webseite
      regeln:
        usuage: /regeln
      teamspeak:
        usuage: /teamspeak
      teamspeak3:
        usuage: /teamspeak3
      mys:
        usuage: /mys
      mys:
        usuage: /mys reload
      mys:
        usuage: /mys on
      links:
        usuage: /links